apiVersion: v1
kind: Pod
metadata:
  name: makedb
  namespace: default
spec:
  containers:
    - image: quay.io/biocontainers/blast:2.7.1--h4422958_6
      command: [ "makeblastdb", "-in", "/data/zebrafish.1.protein.faa", "-dbtype", "prot" ]
      imagePullPolicy: IfNotPresent
      name: makedb
      volumeMounts:
        - mountPath: "/data"
          name: myvol
  dnsPolicy: "ClusterFirst"
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 8.8.4.4
  restartPolicy: Never
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: claim
