apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nxf-vol-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: microk8s-hostpath