apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nxf-vol-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path